### ISSUE TITLE
Not hearing the sweet creamy flatulence

### ISSUE THREAD

**Issue by aetweedie** [D-TUCKER/react-fartscroll#1]
Tried it my app, no errors, no gas.
Tried it in your demo app, can't hear the poots.

**Comment by D-TUCKER** [comment]
Oh no! I will alert our service team to triage this immediately.

**Comment by aetweedie** [comment]
Thank you for your quick response. I have a need for ass sounds on this app and I cannot stand to live another minute without the holy air emanating from my speakers. (I will look at it too and do a PR if I can fix it). Thank you for performing this public service. I will make the Nobel committee aware of this repo, we still have a few weeks before next year's nominations are due.

**Comment by aetweedie** [comment]
Interesting, it just up and started working. I opened the dev tools to see if there were errors and it worked.
